### ISSUE TITLE
Putting the PKGBUILD on the AUR?

### ISSUE THREAD

**Issue by mxmilkiib** [sboukortt/intersect-lv2#2]
Would you like to do that or do you not mind if I do it? :)

**Comment by sboukortt** [comment]
Hi Milkii, and first of all, thank you for your interest. :) I’d be happy to let you upload it if you would like to be the maintainer of the package, but otherwise I can also take care of it if you’d prefer.

**Comment by mxmilkiib** [comment]
https://aur.archlinux.org/packages/intersect.lv2-git

**Comment by sboukortt** [comment]
Great, thank you! :smile: 

Just a small suggestion: if it’s going to be a `-git` package, let’s perhaps give it a `pkgver()` function? For example this one: https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git

> Using the most recent annotated tag reachable from the last commit:
>
> ```bash
> pkgver() {
>   cd "$pkgname"
>   git describe --long | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
> }
> ```
>
> ```
> 2.0.r6.ga17a017
> ```

A non-`-git` package with `#tag=$pkgver` added to the source URL would also be a possibility.

**Comment by mxmilkiib** [comment]
Ah yes, I forgot a `pkgver()` as I have that in the template I didn't use :)

**Comment by sboukortt** [comment]
Excellent, thanks again :relaxed:
